version: '3.7'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgresql
    volumes:
      - /home/apa/vol_docker/zabbix/data:/var/lib/zabbix
      - /home/apa/vol_docker/zabbix/data-snmptraps:/var/lib/zabbix/snmptraps
      - /home/apa/vol_docker/zabbix/data-export:/var/lib/zabbix/export
      #- /home/apa/vol_docker/zabbix/config:/etc/zabbix
    networks:
      - zabbix-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix_db -h postgresql"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql:
    image: postgres:15.8-bookworm
    container_name: pgsql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /home/apa/vol_docker/postgres/data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: unless-stopped
    command: postgres -c 'config_file=/var/lib/postgresql/data/postgresql.conf'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-ubuntu-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - DB_SERVER_HOST=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=${PHP_TZ}
    depends_on:
      - zabbix-server
      - postgresql
    #volumes:
      #- /home/apa/vol_docker/zabbix-web/data:/usr/share/zabbix
      #- /home/apa/vol_docker/zabbix-web/config:/etc/zabbix/web
    networks:
      - zabbix-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  zabbix-agent2:
    image: zabbix/zabbix-agent2:7.0-ubuntu-latest
    container_name: zabbix-agent2
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=zabbix-agent
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=pgsql
      - ZBX_SERVER_PORT=10051
      - ZBX_SERVER_ALLOWED_IPS=127.0.0.1,zabbix-server,172.18.0.0/16
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      - zabbix-net
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "zabbix_get -s 127.0.0.1 -k agent.ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  zabbix-net:
    driver: bridge