version: '3.7'
services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-pgsql:7.0-latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=postgresql
      - POSTGRES_USER=zabbix_proxy
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=zabbix_proxy_db
    depends_on:
      - postgresql
    volumes:
      - ./zabbix_proxy_data:/var/lib/zabbix

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=zabbix_proxy
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=zabbix_proxy_db
    volumes:
      - ./pgsql_proxy_data:/var/lib/postgresql/data