apiVersion: v1
kind: Secret
metadata:
  name: gitlab-basic-auth  #Name of the secret
  annotations:
    tekton.dev/git-0: http://192.168.2.20 #THIS ONE MATTERES!
type: kubernetes.io/basic-auth
stringData:
  username: <YOUR_DATA> #CHANGE IT!
  password: <YOUR_DATA> #CHANGE IT!