apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  source:
  chart: httpbin
  repoURL: https://gitlab.com/api/v4/projects/[project id]/packages/helm/stable   #CHANGED!
  targetRevision: 0.1.0   #CHANGED!
  helm:
    releaseName: httpbin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true