version: '3.3'
services:
  <your-domain.com>:
    image: 'gitlab/gitlab-ce:16.11.6-ce.0'
    restart: unless-stopped
    hostname: <your-domain.com>
    container_name: <your-domain.com>
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://<your-domain.com>:443'
        nginx['enable'] = true
        nginx['listen_https'] = true
        nginx['redirect_http_to_https'] = false
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/fullchain.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/privkey.pem"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'git@<your-domain.com>'
        gitlab_rails['gitlab_email_display_name'] = '<your-domain>Git'
        gitlab_rails['gitlab_email_reply_to'] = 'git@<your-domain.com>'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.<your-domain.com>'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'git@<your-domain.com>'
        gitlab_rails['smtp_password'] = 'Some$PSSWD'
        gitlab_rails['smtp_domain'] = 'mail.<your-domain.com>'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        letsencrypt['enabled'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        nginx['real_ip_header'] = 'X-Real-IP'
        nginx['real_ip_recursive'] = 'on'
        nginx['client_max_body_size'] = '0'
        registry_external_url 'https://rgtrbnk.<your-domain.com>'
        registry['enable'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        registry_nginx['real_ip_header'] = 'X-Real-IP'
        registry_nginx['real_ip_recursive'] = 'on'
        registry_nginx['client_max_body_size'] = '0'
    ports:
      - '5050:5050'
      - '443:443'
      - '80:8070'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"