{
 "title": "SNMP Interfaces",
 "description": "A sample template from https://sbcode.net/grafana/import-snmp-influxdb-telegraf-dashboard/",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source Host",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\r\n  |> group()\r\n  |> distinct(column: \"source\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 86400.0 / 100.0 }))\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.source}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Interface",
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n    |> range(start: -1m)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n    |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field}))\r\n    |> last()   \r\n"
    }
   ]
  },
  {
   "title": "In Octets",
   "type": "timeseries",
   "description": "The total number of octets received on the interface, including framing characters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInOctets\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.ifDescr}))\r\n  "
    }
   ]
  },
  {
   "title": "Out Octets",
   "type": "timeseries",
   "description": "The total number of octets transmitted out of the interface, including framing characters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifOutOctets\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.ifDescr}))"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "description": "The number of inbound packets which were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol. One possible reason for discarding such a packet could be to free up buffer space",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInDiscards\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.ifDescr}))\r\n  "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "The number of inbound packets that contained errors preventing them from being deliverable to a higher-layer protocol.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInErrors\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.ifDescr}))\r\n  "
    }
   ]
  }
 ]
}