web:
  image:
    repository: ${image}
    tag: latest
  imagePullSecrets:
  - name: harbor-registry-secret
  service:
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prd
    hosts:
    - host: ${url}
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: ${name}-tls
      hosts:
      - ${url}
