apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}-${instance}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: frontend-${instance}
  source:
    repoURL: 'https://${gitlabUrl}/devops/apps-templates.git'
    path: frontend/${instance}/${name}
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend-${name}-${instance}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - Prune=true
      - SelfHeal=false
