apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  source:
  chart: httpbin
  repoURL: https://matheusfm.dev/charts
  targetRevision: 0.1.1
  helm:
    releaseName: httpbin
    values: |   #Override default values of this helm chart. Pipe here means that values are being added using string, not objects that were used before
      service:
        type: NodePort
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true