version: '3.8'
services:
  pgsql-dev:
    image: postgres
    container_name: pgsql-dev
    environment:
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-docker:/var/lib/postgresql/data
      - /path/to/custom/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.95'    # Limits CPU usage to 95% of one core
          memory: 950M     # Limits memory usage to 950MB
    restart: unless-stopped