version: '3.7' 
services:
  zabbix-proxy:
    image: zabbix-proxy:7.0
    container_name: zabbix-proxy
    hostname: ZBX-PROXY
    ports:
      - "${PORT_ZBX_PROXY}:10051"
    environment:
      # Proxy-specific DB settings
      - DB_SERVER_HOST=postgresql
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Proxy settings
      - ZBX_HOSTNAME="ZBX-PROXY"
      - ZBX_SERVER_HOST="zabbix-server"
      - ZBX_CONFIGFREQUENCY=3600
      - ZBX_PROXYMODE=0 # 0 = active, 1 = passive
    depends_on:
      - postgresql
    #volumes:
      #- /home/apa/zabbix_proxy_v7/vol_docker/zabbix-proxy/lib:/var/lib/zabbix
      #- /home/apa/zabbix_proxy_v7/vol_docker/zabbix-proxy/config/zabbix_proxy.conf:/etc/zabbix/zabbix_proxy.conf
    networks:
      - zabbix-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgresql"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql:
    image: postgres:15.8-bookworm
    container_name: pgsql
    ports:
      - "${PORT_PGSQL}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /home/apa/zabbix_proxy_v7/vol_docker/postgres/data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: unless-stopped
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  zabbix-net:
    driver: bridge