#TriggerTemplate: reates a pipeline run using the Git repository information received from the TriggerBinding resource.

apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata:
  name: vote-app    #Unique name to identify the TriggerTemplate resource.
spec:
  params:     #Parameters supplied by the TriggerBinding resource.
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: pipelines-1.5
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:    #List of templates that specify the way resources must be created using the parameters received through the TriggerBinding or EventListener resources.
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: build-deploy-$(tt.params.git-repo-name)-$(uid)
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: build-and-deploy
      params:
      - name: deployment-name
        value: $(tt.params.git-repo-name)
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/$(tt.params.git-repo-name)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
         spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi