version: "3.7"
services:
  zabbix-server:
    image: zabbix-server-with-python:latest
    container_name: zabbix-server
    hostname: ZBX-DOCKER
    ports:
      - "${PORT_ZBX_SERVER}:10051"
    environment:
      #DB Settings
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - DB_SERVER_PORT=${DB_SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      #PSK (Pre-Shared Key) Settings
      - ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY}
      - ZBX_TLSPSKKEY=${ZBX_TLSPSKKEY}
      - ZBX_TLSACCEPT=psk,unencrypted
      #SNMP Traps
      - ZBX_ENABLE_SNMP_TRAPS=true
    depends_on:
      - postgresql
    volumes:
      - /opt/zabbix_stack/vol_docker/zabbix-server/lib:/usr/lib/zabbix
      - /opt/zabbix_stack/vol_docker/zabbix-server/config/zabbix_server.conf:/etc/zabbix/zabbix_server.conf
      #- /opt/zabbix_stack/vol_docker/zabbix-server/data:/var/lib/zabbix
      #- /opt/zabbix_stack/vol_docker/zabbix-server/config:/etc/zabbix
      #- /opt/zabbix_stack/vol_docker/zabbix-server/share:/usr/share/zabbix
    networks:
      - zabbix-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix -h postgresql"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql:
    image: postgres:15.8-bookworm
    container_name: pgsql
    ports:
      - "${PORT_PGSQL}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /data/dockerized_postgresql/pgsql_docker_volume/data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: unless-stopped
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix"]
      interval: 30s
      timeout: 10s
      retries: 5

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-ubuntu-latest
    container_name: zabbix-web
    ports:
      - "${PORT_ZBX_WEB}:8080"
      - "${PORT_ZBX_WEB_SSL}:8443"
    environment:
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - DB_SERVER_PORT=${DB_SERVER_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=${PHP_TZ}
    depends_on:
      - zabbix-server
      - postgresql
    #volumes:
      #- /opt/zabbix_stack/vol_docker/zabbix-web/data:/usr/share/zabbix
      #- /opt/zabbix_stack/vol_docker/zabbix-web/config:/etc/zabbix/web
    networks:
      - zabbix-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

#  zabbix-agent2:
#    image: zabbix/zabbix-agent2:7.0-ubuntu-latest
#    container_name: zabbix-agent2
#    environment:
#      #Zabbix Server Settings
#      - ZBX_SERVER_HOST=zabbix-server,127.0.0.1,172.18.0.0/16
#      - ZBX_HOSTNAME=zabbix-agent
#      - ZBX_SERVER_PORT=10051
#      - ZBX_SERVER_ALLOWED_IPS=127.0.0.1,zabbix-server,172.18.0.0/16
#      #DB Settings
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_HOST=pgsql
#      #PSK (Pre-Shared Key) Settings
#      - ZBX_TLSACCEPT=psk,unencrypted
#     - ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY}
#      - ZBX_TLSPSKKEY=${ZBX_TLSPSKKEY}
#    depends_on:
#      - zabbix-server
#    ports:
#      - "${PORT_ZBX_AGENT}:10050"
#    networks:
#      - zabbix-net
#    restart: unless-stopped
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run
#    privileged: true
#    healthcheck:
#      test: ["CMD-SHELL", "zabbix_get -s 127.0.0.1 -k agent.ping || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

networks:
  zabbix-net:
    driver: bridge