version: '3.7'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu-latest
    container_name: zabbix-server-pgsql
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=postgresql
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=zabbix_db
    depends_on:
      - postgresql
    volumes:
      - /home/apa/vol_docker/zabbix/data:/var/lib/zabbix
      - /home/apa/vol_docker/zabbix/config:/etc/zabbix/
    restart: unless-stopped

  postgresql:
    image: postgres:15.8-bookworm
    container_name: pgsql-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=zabbix_db
    volumes:
      - /home/apa/vol_docker/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    command: /bin/bash -c "apt-get update && apt-get install -y postgresql-client && docker-entrypoint.sh postgres -c config_file=/var/lib/postgresql/data/postgresql.conf"

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-ubuntu-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - DB_SERVER_HOST=postgresql
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=zabbix_db
      - ZBX_SERVER_HOST=zabbix-server-pgsql
    depends_on:
      - zabbix-server
      - postgresql
    volumes:
      - /home/apa/vol_docker/zabbix-web/config:/etc/zabbix/web
    restart: unless-stopped

  zabbix-agent2:
    image: zabbix/zabbix-agent2:7.0-ubuntu-latest
    container_name: zabbix-agent2
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    restart: unless-stopped