# opensearch-exporter.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-exporter
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-exporter
  template:
    metadata:
      labels:
        app: opensearch-exporter
    spec:
      containers:
        - name: opensearch-exporter
          image: registry.eniac-tech.com/p8s_exporters/elasticsearch-exporter:v1.7.0
          args:
            - "--es.uri=http://opensearch-cluster-master:9200"
            - "--es.all"
            - "--es.indices"
            - "--es.indices_settings"
            - "--es.shards"
            - "--collector.snapshots"
            - "--collector.clustersettings"
            - "--web.listen-address=:9114"
          ports:
            - containerPort: 9114
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-exporter
  namespace: graylog
  labels:
    app: opensearch-exporter
spec:
  selector:
    app: opensearch-exporter
  ports:
    - name: metrics
      port: 9114
      targetPort: 9114