# servicemonitors.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opensearch-exporter
  namespace: graylog
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: opensearch-exporter
  namespaceSelector:
    matchNames: ["graylog"]
  endpoints:
    - port: metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: graylog-metrics
  namespace: graylog
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graylog
  namespaceSelector:
    matchNames: ["graylog"]
  endpoints:
    - port: metrics
      interval: 30s